### ISSUE TITLE
ACK com tamanho errado

### ISSUE THREAD

**Issue by fasunna** [brtos/brtos-unet#6]
Olá!

Gostaria de confirmar se o tamanho do pacote ACK não está sendo definido errado na função:
"link_packet_create_ack", pois até onde verifiquei, e com as conversas com Gustavo, a confirmação não utiliza o endereçamento de 64 bits. Portanto, o tamanho do pacote total deveria ser de 14 bytes, não 30 como está definido no código.

UNET_NWK_HEADER_SIZE = 20 pois contabiliza os endereçamentos de 64 bits.

Grato!
Att Fabricio

**Comment by barriquello** [comment]
Olá Fabrício, realmente os endereços de 64b não usados neste caso. Apenas para facilitar o código usando um cabeçalho de rede de tamanho fixo (20B) foram mantidos. Daria para remover neste caso, mas teria que passar pelos testes para ver se isso não causa algum bug devido a desalinhamento, ou outro problema.

**Comment by barriquello** [comment]
Fechado. Pode ser implementado como melhoria futura, mas não causa erro.
